### ISSUE TITLE
[BUG] App won't launch when unable to access accelerometer sensor 

### ISSUE THREAD

**Issue by Tisckkytt** [vishnuraghavb/EnRecipes#30] opened 2021-01-31 09:00 UTC
**Describe the bug**
Not sure if I should call it a bug, but app will crash at launch. My system sensors are currently dead on the setup I'm running but the question being, why accelerometer is necessary in the first place for this app? 

**To Reproduce**
1. Kill off sensors
2. Install & launch this app

**Expected behavior**
Is to run the app without crashing

**Screenshots**

**Device information (please complete the following information):**
 - Android Version: 11
 - EnRecipes Version(as in app's about page):  1.3.0 from playstore

**Additional context**
Stack trace:

> 

`FATAL EXCEPTION: main
Process: com.vishnuraghav.enrecipes, PID: 2596
com.tns.NativeScriptException: Calling js method onCreateView failed
Error: Could get accelerometer sensor.
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)`

**Comment by vishnuraghavb** [comment] 2021-01-31 09:27
May be because, it requires the sensor to detect the portrait orientation. It can be either normal or reverse portrait based on the device sensor and your sensor preference. If you have locked sensor-based rotation, this behaves the same as portrait, otherwise it behaves the same as sensorPortrait. But in your case, the sensors are turned off/dead. So EnRecipes is unable to start. 

I've set `android:screenOrientation="userPortrait"` instead of `portrait`(which doesn't require sensor data) in the android manifest. That's the reason for your issue. I will fix this line to let users like you to use EnRecipes without the need for accelerometer.

**Comment by vishnuraghavb** [comment] 2021-01-31 13:02
And also the "shake to view random recipe" feature makes use of the accelerometer to detect device shake. I will do a workaround for that to make it work on devices with no sensors. Thanks!

**Comment by vishnuraghavb** [comment] 2021-01-31 14:23
Hi, I've tried to reproduce your issue using the Android emulator with all the sensors turned off (I've turned off sensors using this guide: https://www.howtogeek.com/691619/how-to-turn-off-all-your-android-phones-sensors-in-one-tap). But everything is working fine for me, no crashes. Can you try clearing the app data under settings and give it a try? Thanks!

**Comment by Nico207** [comment] 2021-02-10 22:51
I can reproduce this bug.
I use XprivacyLua which, for a given application, can block access to sensor (and many other thing).
If I block sensors, the app crash on startup. When sensors are unblocked, the app works fine.

**Comment by vishnuraghavb** [comment] 2021-02-12 05:27
Thanks for your information! I'll try to fix this issue soon.

**Comment by vishnuraghavb** [comment] 2021-04-23 15:00
Fixed in [v1.3.2 release](https://github.com/vishnuraghavb/EnRecipes/releases/tag/v1.3.2)

**Closed by vishnuraghavb** 2021-04-23 15:00 UTC
Labels: bug

**Comment by vishnuraghavb** [comment] 2021-04-25 09:25
Hi @Tisckkytt and @Nico207 
Thanks for suggesting XprivacyLua to reproduce this issue. I would like to inform you that this has been fixed!
